-- schema.sql — reference schema matching the live Supabase project.
-- The `tasks` table already exists in production (created from earlier work),
-- so this does not need to be re-run there. It documents the real structure
-- and lets a fresh Supabase project be bootstrapped the same way.
--
-- Multi-user: each row belongs to exactly one auth.users account via user_id,
-- enforced by RLS. See migration.sql for how the live project moved from a
-- single shared anon-accessible table to this per-user model.

create table if not exists public.tasks (
  id                       bigint generated by default as identity primary key,
  user_id                  uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name                     text not null,
  content                  text not null default '',
  -- Array of { id: string, date: 'YYYY-MM-DD', target: string, content: string, completed: boolean }.
  milestones               jsonb not null default '[]'::jsonb,
  is_completed             boolean not null default false,
  -- Index (into `milestones`) of the first incomplete milestone; kept in sync by the app
  -- whenever milestones change, not edited directly by the user.
  current_milestone_index  integer not null default 0,
  created_at               timestamptz not null default now(),
  constraint name_not_empty check (char_length(trim(name)) > 0)
);

comment on table public.tasks is '업무 관리: 사용자별 업무/마일스톤 추적.';

-- Row Level Security: each authenticated user can only see and modify their own rows.
alter table public.tasks enable row level security;

drop policy if exists "Users manage own tasks" on public.tasks;
create policy "Users manage own tasks"
  on public.tasks
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
