-- schema.sql — reference schema matching the live Supabase project.
-- The `tasks` table already exists in production (created from earlier work),
-- so this does not need to be re-run there. It documents the real structure
-- and lets a fresh Supabase project be bootstrapped the same way.

create table if not exists public.tasks (
  id                       bigint generated by default as identity primary key,
  name                     text not null,
  content                  text not null default '',
  -- Array of { id: string, date: 'YYYY-MM-DD', target: string, content: string, completed: boolean }.
  milestones               jsonb not null default '[]'::jsonb,
  is_completed             boolean not null default false,
  -- Index (into `milestones`) of the first incomplete milestone; kept in sync by the app
  -- whenever milestones change, not edited directly by the user.
  current_milestone_index  integer not null default 0,
  created_at               timestamptz not null default now(),
  constraint name_not_empty check (char_length(trim(name)) > 0)
);

comment on table public.tasks is '업무 관리: 업무별 마일스톤 추적.';

-- Row Level Security: single-user app, no auth yet, anon key only.
-- RLS stays enabled with an explicit permissive policy (rather than disabling RLS)
-- so Supabase's security advisor doesn't flag it, and so a future auth-based
-- policy is a simple edit instead of a structural on/off flip.
alter table public.tasks enable row level security;

drop policy if exists "Allow anon full access to tasks" on public.tasks;
create policy "Allow anon full access to tasks"
  on public.tasks
  for all
  to anon
  using (true)
  with check (true);
